@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="./.." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include %get_variable_value("RELATIVE_INCLUDE")/C4_Container.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!endif

SHOW_PERSON_OUTLINE()
AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#335DA5", $shape=EightSidedShape())

title Context diagram for Duolingo

Person(user, Language Enthusiast, "Could be a language learner, language expert or an educator.")

System_Boundary(c1, "") {
    Container(web_app, "Web Application", "React", "Provides the language learning or teaching functionality to language enthusiast via their web browser")
    Container(mobile_app, "Mobile Application", "Swift for iOS and Java for Android", "Provides the language learning or teaching functionality to language enthusiast via their mobile device")
    ContainerDb(database, "Database", "DynamoDB", "Stores user registration information, learning progress, access logs, etc.")
    Container(backend_api, "Duolingo Application", "Python, Amazon WebServices", "Provides application backend functionality", $tags="backendContainer")
    Container(gamification, "Gamification Process", "AI, ML", "Stores all of the ML Models on basis of which user gets tests rendered. Amplifies the user learning process.")
}

System_Ext(email_system, "E-Mail System", "On Registration or course completion Email is sent out to the user.")

Rel(user, web_app, "Log in/ SignUp")
Rel(user, mobile_app, "Log in/ SignUp")

Rel(web_app, backend_api, "Uses")
Rel(mobile_app, backend_api, "Uses")

Rel_Back(user, email_system, "Sends e-mails to")
Rel_Back(email_system, backend_api, "Sends e-mails using")
Rel_Neighbor(database, backend_api, "Reads from and writes to")
Rel(backend_api, gamification, "Uses")

@enduml